[FIX] account_statement_import_online: Avoid error in journal unlink test
There's a chance that the recently created journal is selected for a
payment acquirer thanks to this open compute:

https://github.com/OCA/OCB/blob/c5346c04a2e24fe236312988f173f166881b3567/addons/payment/models/payment_acquirer.py#L171-L180

and thus, when trying to unlink it, we get:

odoo.exceptions.UserError: You must first deactivate a payment acquirer before deleting its journal.

For avoiding this situation in integration tests, we do:

- Assign a higher sequence for being the last existing journal.
- Remove the payment method lines associated to the journal.